### ISSUE TITLE
start_stop step is randomly failed in regression tests

### ISSUE THREAD

**Issue by tilkow** [dalibo/emaj#13]
Hi Philippe,

The line below appears randomly when running start_stop step in the regression tests, which creates (or not) a difference when comparing ''expected/start_stop.out'' and ''results/start_stop.out''

<code>
!  hist_id |   hist_function    |       hist_event        |                  hist_object                  |         regexp_replace          | hist_u
ser 
! ---------+--------------------+-------------------------+-----------------------------------------------+---------------------------------+-------
----
!     1008 | DISABLE_PROTECTION | EVENT TRIGGERS DISABLED |                                               | <none>                          | postgr
</code>

Best regards

**Comment by beaud76** [comment]
Thanks for having reported this.
I also get this difference from times to times when running regression tests. But I have been to lazy to solve this. And I know this is not a real problem. But it's now time to solve the issue.
This is due to the mechanism that purges the emaj_history table. Among the parameters that enter into account, there is a history retention delay. At the beginning of the start_stop script, the history is supposed to be cleared to minimize the impact of a test scenario change from one script to the others. But in this case the purge comes a little bit late. Depending on the system which runs the test, the row you noticed may be purged or not.
I will try to fix that more properly.

**Comment by beaud76** [comment]
The commit d670c926a688cfd5a7a7776458410d8999bc8093 is supposed to improve the results stability. 
tilkow, can you also test on your side ?

**Comment by tilkow** [comment]
I just tested several times and the difference reported before the commit https://github.com/beaud76/emaj/commit/d670c926a688cfd5a7a7776458410d8999bc8093 is no longer present, the "start_stop" test is ok!
Thanks
