### ISSUE TITLE
Question: Is it possible to store additional info when logging

### ISSUE THREAD

**Issue by stlbucket** [dalibo/emaj#26]
In particular, I'm using https://www.graphile.org/postgraphile/, which passes user info via settings.  so to get current user i can call something like:

current_setting('jwt.claims.contact_id')

would i be able to modify the logging tables/triggers to collect this info as well?

**Comment by beaud76** [comment]
Hi, thanks for your message. Yes, you should be able to add a column in your log tables, by hacking emaj. As I am currently in vacation and without any material to test something, I can't be very sure. But normally, if you change the _create_tbl() function and add a 'add column xxx default current_setting(...)' clause to the alter table statement, it should work. I think your new column name must start with emaj_ so that the check functions don't detect discrepancy between log tables and application tables. I am interested by your test. I believe that it would be worth a chapter into the documentation. I also considered to add a sort of hook to handle such a case, but it would slow down the logging mechanism, which is an important aspect. I will be back in about 10 days to help you more efficiently if needed. KR. Philippe.

**Comment by beaud76** [comment]
Oups, I realize that the text editor has eaten the underscore at the beginning of the create_tbl() and column name prefix.

**Comment by beaud76** [comment]
Thinking a little bit more seriously, I believe we should be able to set up a new parameter in the emaj_param table to define, if needed, a customization of the log tables, such as an add column clause. If the value of this additional column is set using a default clause, there is no impact on log triggers and the performance penalty would be marginal.

**Comment by beaud76** [comment]
Hi stlbucket,
The commit 2b597caa5e022b7e970690e1192217132d04c98a implements this idea.
You can find how to use it in the updated [documentation](https://emaj.readthedocs.io/fr/latest/logTables.html)
Fell free to try and tell me what you think about it.
Philippe.
