### ISSUE TITLE
Issue during auto drop unused log tables

### ISSUE THREAD

**Issue by dhaddadi** [dalibo/emaj#37]
this is the output when perform delete before mark statement 

newton@newton_pic(retail01)=> SELECT emaj.emaj_delete_before_mark_group('newton_datalake', 'Mark-3');
ERROR:  must be owner of relation newton_dhi_test_1_log_1
CONTEXT:  SQL statement "DROP TABLE IF EXISTS emaj.newton_dhi_test_1_log_1 CASCADE"

**Comment by beaud76** [comment]
Thanks Djamel for having reported this issue.
I have reproduced the problem and it is clearly a bug: an internal function was not declared as SECURITY DEFINER.
This is fixed by the commit 7e7faeb9ba959cfb0de863ae8cb65bdb706b2f4d, that will be included in the next release (soon !).
As a workaround, you can:
- either execute your sql statement with a superuser role
- or execute the following statement as superuser to fix the function:
    ALTER FUNCTION emaj._delete_before_mark_group(TEXT,TEXT) SECURITY DEFINER;
