### ISSUE TITLE
Avoid Postgres regress tool

### ISSUE THREAD

**Issue by tilkow** [dalibo/emaj#7]
The E-maj regress.sh tool needs  the Postgres regress binary that has to be created from the Postgres's sources.
The E-maj regress.sh tool could perform the test by itself.

**Comment by beaud76** [comment]
You are right. Running the E-Maj regression tests currently needs the Postgres pg_regress tool that is generally not available with usual postgres packages. It's often included in devel or test packages.
So that would be more convenient to not being obliged to install additional postgres packages. 
Feel free to propose an enhancement of the regress.sh tool ;-)

**Comment by beaud76** [comment]
Solved with commit 27b020b6aa6c25f22ebf8b0cffc4628edb35c951.
